# Tripal Cultivate Phenotypes Configuration/Settings Schema.

trpcultivate_phenotypes.settings:
  type: config_object
  mapping:
    trpcultivate:
      type: mapping
      label: 'Tripal Cultivate Phenotypes Configuration'
      mapping:
        phenotypes:
          type: mapping
          label: 'Phenotypes Global Configuration'
          mapping:
            directory:
              type: mapping
              label: 'Directory structure'
              mapping:
                watermark:
                  type: path
                  label: 'Directory: watermark image'
                data_file:
                  type: path
                  label: 'Directory: data collection file'
                data_backup:
                  type: path
                  label: 'Directory: user data collection file backup'
                data_env:
                  type: path
                  label: 'Directory: environment data file'
                trait_photo:
                  type: path
                  label: 'Trait images'
            r_config:
              type: mapping
              label: 'R Translation Rules'
              mapping:
                words:
                  type: sequence
                  label: 'R Rules for words to remove'
                  sequence:
                    type: string
                    label: 'Word to remove'
                chars:
                  type: sequence
                  label: 'R Rules for characters to remove'
                  sequence:
                    type: string
                    label: 'Character to remove'
                replace:
                  type: sequence
                  label: 'R Rules for match and replace'
                  sequence:
                    type: string
                    label: 'Match and replace'
            watermark:
              type: mapping
              label: 'Watermark Charts'
              mapping:
                charts:
                  type: boolean
                  label: 'Watermark all charts'
                image:
                  type: uri
                  label: 'Watermark image file'
                  nullable: true
                file_ext:
                  type: sequence
                  label: 'Watermark image valid file extensions'
                  sequence:
                    type: string
                    label: 'File extensions'
            ontology:
              type: mapping
              label: 'CV Terms, Terms, and DB'
              mapping:
                terms:
                  type: mapping
                  label: 'Terms used in inserting data'
                  mapping:
                    data_collector:
                      type: integer
                      label: 'CV Term: Data collector'
                    entry: 
                      type: integer
                      label: 'CV Term: Phenotype entry number'
                    genus: 
                      type: integer
                      label: 'CV Term: Genus'
                    location: 
                      type: integer
                      label: 'CV Term: Phenotyping experiment location'
                    method: 
                      type: integer
                      label: 'CV Term: Phenotyping collection method'
                    name:
                      type: integer
                      label: 'CV Term: Germplasm/line name'
                    experiment_container:
                      type: integer
                      label: 'CV Term: Phenotyping plot number'
                    unit_to_method_relationship_type:
                      type: integer
                      label: 'CV Term: Unit - Method relationship'
                    method_to_trait_relationship_type:
                      type: integer
                      label: 'CV Term: Method - Trait relationship'  
                    experiment_replicate:
                      type: integer
                      label: 'CV Term: Phenotyping replicate'
                    unit:
                      type: integer
                      label: 'CV Term: Trait unit'
                    experiment_year:
                      type: integer
                      label: 'CV Term: Phenotyping year'
                cvdbon:
                  type: sequence
                  label: 'CV, DB and Ontology'
                  description: 'The key of this sequence is the sanitized genus and the value mapping indicates the values for this genus.'
                  nullable: True
                  sequence:
                    type: mapping
                    label: 'Genus-based CV, DB and Ontology'
                    mapping:
                      trait:
                        type: integer
                        label: 'CV: traits'
                      method:
                        type: integer
                        label: 'CV: methods'
                      unit:
                        type: integer
                        label: 'CV: unit'
                      database:
                        type: integer
                        label: 'Database'
                      crop_ontology:
                        type: integer
                        label: 'CV: ontology'
                allownew:
                  type: boolean
                  label: 'Allow new traits added during upload'
        phenoshare:
          type: string
          label: 'Phenotypes Share (Analyzed) Configuration'
        phenocollect:
          type: string
          label: 'Phenotypes Collect (Raw) Configuration'
        
        # Tripal Phenotypes default ontology/term values.
        default_terms:
          type: config_entity
          label: 'Configuration Entity Collection'
          mapping:
            term_set:
              type: sequence
              label: 'Set of cv and terms'
              sequence:
                type: mapping
                mapping: 
                  name:
                    type: string
                    label: 'CV name'
                  definition:
                    type: string
                    label: 'Definition'
                  terms:
                    type: sequence
                    sequence:
                      type: mapping
                      mapping:
                        config_map:
                          type: string
                          label: 'This term maps to which configuration variable name'
                        id:
                          type: string
                          label: 'Term id'
                        name:
                          type: string
                          label: 'Term name'
                        definition:
                          type: string
                          label: 'Term definition'