# Tripal Cultivate Phenotypes Configuration/Settings Schema.

trpcultivate_phenotypes.settings:
  type: config_object
  mapping:
    trpcultivate:
      type: mapping
      label: 'Tripal Cultivate Phenotypes Configuration'
      mapping:
        phenotypes:
          type: mapping
          label: 'Phenotypes Global Configuration'
          mapping:
            directory:
              type: mapping
              label: 'Directory structure'
              mapping:
                watermark:
                  type: path
                  label: 'Directory: watermark image'
                data_file:
                  type: path
                  label: 'Directory: data collection file'
                data_backup:
                  type: path
                  label: 'Directory: user data collection file backup'
                data_env:
                  type: path
                  label: 'Directory: environment data file'
                trait_photo:
                  type: path
                  label: 'Trait images'
            r_config:
              type: mapping
              label: 'R Translation Rules'
              mapping:
                words:
                  type: sequence
                  label: 'R Rules for words to remove'
                  sequence:
                    type: string
                    label: 'Word to remove'
                chars:
                  type: sequence
                  label: 'R Rules for characters to remove'
                  sequence:
                    type: string
                    label: 'Character to remove'
                replace:
                  type: sequence
                  label: 'R Rules for match and replace'
                  sequence:
                    type: string
                    label: 'Match and replace'
            watermark:
              type: mapping
              label: 'Watermark Charts'
              mapping:
                charts:
                  type: boolean
                  label: 'Watermark all charts'
                image:
                  type: uri
                  label: 'Watermark image file'
                  nullable: true
                file_ext:
                  type: sequence
                  label: 'Watermark image valid file extensions'
                  sequence:
                    type: string
                    label: 'File extensions'
        phenoshare:
          type: string
          label: 'Phenotypes Share (Analyzed) Configuration'
        phenocollect:
          type: string
          label: 'Phenotypes Collect (Raw) Configuration'