# Run some PHPUnit tests
name: Test Coverage
on: [push, workflow_dispatch]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run Automated testing + report coverage
        uses: tripal/test-tripal-action@v1.6
        with:
          directory-name: 'TripalCultivate-Phenotypes'
          modules: 'trpcultivate_phenotypes trpcultivate_phenocollect trpcultivate_phenoshare'
          build-image: TRUE
          dockerfile: 'Dockerfile'
          php-version: 8.3
          pgsql-version: 16
          drupal-version: 10.4.x-dev
          codeclimate-reporter-id: ${{ secrets.CODECLIMATE_TEST_REPORTER_ID }}
