# Run some PHPUnit tests
name: Test Coverage
on: [push, workflow_dispatch]

env:
  drupal_version: 10.4.x-dev
  php_version: 8.3
  pgsql_version: 16

jobs:
  run-coverage:
    name: "Drupal $drupal_version - PHP $php_version - PostgreSQL $pgsql_version"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run Automated testing + report coverage
        uses: tripal/test-tripal-action@v1.6
        with:
          directory-name: 'TripalCultivate-Phenotypes'
          modules: 'trpcultivate_phenotypes trpcultivate_phenocollect trpcultivate_phenoshare'
          build-image: TRUE
          dockerfile: 'Dockerfile'
          php-version: $php_version
          pgsql-version: $pgsql_version
          drupal-version: $drupal_version
          codeclimate-reporter-id: ${{ secrets.CODECLIMATE_TEST_REPORTER_ID }}
