name: PHPUnit
on:
  push:
    branches:
      - 4.x
      - g5.18-workflows
jobs:
  grid-3C:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run Automated testing
        uses: tripal/test-tripal-action@v1.0
        with:
          directory-name: 'TripalCultivate-Phenotypes'
          modules: 'trpcultivate_phenotypes trpcultivate_phenocollect trpcultivate_phenoshare'
          php-version: '8.2'
          pgsql-version: '13'
          drupal-version: '10.0.x-dev'
