name: PHPUnit
on:
  push:
    branches:
      - 4.x

jobs:
  grid-2B:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run Automated testing
        uses: tripal/test-tripal-action@v1.5
        with:
          directory-name: 'TripalCultivate-Phenotypes'
          modules: 'trpcultivate_phenotypes trpcultivate_phenocollect trpcultivate_phenoshare'
          build-image: TRUE
          dockerfile: 'Dockerfile'
          php-version: '8.2'
          pgsql-version: '16'
          drupal-version: '10.4.x-dev'
